### ISSUE TITLE
Tests have not been passed

### ISSUE THREAD

**Issue by eihigh** [sugawarayuuta/sonnet#1]
There are no tests in this repository.

I ported some of the tests that come with the standard `encoding/json` and the tests did not seem to pass.

You can check this by running the `go test -v` command on [this branch](https://github.com/eihigh/sonnet/tree/tests). As these tests do not pass, this library is considered incompatible with the standard one.

**Comment by itchyny** [comment]
Here's a list of discrepancies I found manually.

### String escape sequences
This package does not unescape JSON escape sequences like `"\t"`.
```go
func TestDecode(t *testing.T) {
	bs := []byte(`"\t"`)
	d := NewDecoder(bytes.NewBuffer(bs))
	var v any
	err := d.Decode(&v)
	if err != nil {
		t.Fatal(err)
	}
	if v != "\t" {
		t.Fatalf("%#v\n", v)
	}
}
```

### Large floating numbers
This package does not support decoding large floating numbers.
```go
func TestDecode(t *testing.T) {
	bs := []byte(`10000000000000000000.0`)
	d := NewDecoder(bytes.NewBuffer(bs))
	var v any
	err := d.Decode(&v)
	if err != nil {
		t.Fatal(err)
	}
	if v != 1e19 {
		t.Fatalf("%#v\n", v)
	}
}
```

### Invalid floating numbers
This package does not reject invalid floating numbers like `1..2` or `..`.
```go
func TestDecode(t *testing.T) {
	bs := []byte(`1e.2`)
	d := NewDecoder(bytes.NewBuffer(bs))
	var v any
	err := d.Decode(&v)
	if err == nil {
		t.Fatal("should raise error")
	}
}
```

**Comment by sugawarayuuta** [comment]
the first issue in the first repo! thank you for the contribution!
i'm planning to add tests and fuzz tests in the next commit that i have been working on.

about the int/uint/float number parsing, im planning to do a fallback (will use strconv standard library) when the number gets too big.

**Comment by itchyny** [comment]
Great job, I confirmed that the cases are fixed.
