### ISSUE TITLE
check correctness of hex sequences

### ISSUE THREAD

**Issue by LeGEC** [sugawarayuuta/sonnet#11]
https://github.com/sugawarayuuta/sonnet/blob/17b81fde02070a3959e628f97ccda86881ff8173/reader.go#L262

From reading the code: it looks like, after reading a `\u` within a string, when the parser expects to read a 4 characters hex sequence `\uXXXX`:

* a check is made to make sure 4 bytes can be read from the input
* **Bug**: but no check is made to check that these 4 characters are actually hex characters

The decoder will accept the following sequences: `...\uOUCH...` or `...\u","f...` without raising an error

**Comment by sugawarayuuta** [comment]
This has been fixed. You can try it [here at the playground](https://go.dev/play/p/E46tGOGP0Jf).  Let me know if I can close this issue. if you have found other problems, file a new issue. Thanks again.
